timetable_planner/routes.py
from flask import Blueprint,redirect,render_template,url_for,current_app,flash,session,abort
from timetable_planner.models import User,Timetable,Subject
from timetable_planner.forms import LoginForm,RegisterForm,AddSubject,AddTimetable
from passlib.hash import pbkdf2_sha256
from dataclasses import asdict
import uuid
import functools
import datetime

pages=Blueprint("pages",__name__,template_folder="template",static_folder="static")

def login_required(route):
    @functools.wraps(route)
    def route_wrapper(*args,**kwargs):
        if session.get("email") is None:
            return redirect(url_for(".login"))
        return route(*args,**kwargs)
    return route_wrapper


@pages.route("/",methods=["GET","POST"])
@login_required
def index():
    user_data=current_app.db.user.find_one({"_id":session.get("_id")})
    user=User(**user_data)
    timetable_data=[current_app.db.timetable.find_one({"_id":_id}) for _id in user.timetables][::-1]
    timetables=[Timetable(**timetable) for timetable in timetable_data]
    form=AddTimetable()
    if form.validate_on_submit():
        timetable=Timetable(
            _id=uuid.uuid4().hex,
            name=(form.name.data).capitalize()
        )
        current_app.db.timetable.insert_one(asdict(timetable))
        current_app.db.user.update_one({"_id":session["_id"]},{"$push":{"timetables":timetable._id}})
        return redirect(url_for(".index"))

    return render_template("index.html",title="Timetable Planner",timetable_data=timetables,form=form)

@pages.route("/login",methods=["GET","POST"])
def login():
    if session.get("email"):
        return redirect(url_for(".index"))
    form=LoginForm()
    if form.validate_on_submit():
        user_data=current_app.db.user.find_one({"email":form.email.data})
        if not user_data:
            flash("Login credentials not correct",category="danger")
            return redirect(url_for(".login"))
        user=User(**user_data)

        if user and pbkdf2_sha256.verify(form.password.data,user.password):
            session["_id"]=user._id
            session["email"]=user.email
            return redirect(url_for(".index"))
        flash("Login credentials not correct",category="danger")    
    return render_template("login.html",title="Timetable Planner - Login",form=form)

@pages.route("/register",methods=["GET","POST"])
def register():
    if session.get("email"):
        return redirect(url_for(".index"))
    
    form=RegisterForm()
    if form.validate_on_submit():
        if current_app.db.user.find_one({"email":form.email.data}):
            flash("Account already exist with this email","danger")
            print("not allowed")
            return redirect(url_for(".register"))
        user=User(
            _id=uuid.uuid4().hex,
            email=form.email.data,
            password=pbkdf2_sha256.hash(form.password.data)
        )
        current_app.db.user.insert_one(asdict(user))
        flash("User Registered Succesfully","success")
        return redirect(url_for(".index"))
    return render_template("register.html",title="Timetable Planner - Register",form=form)

@pages.route("/logout")
def logout():
    session.clear()
    return redirect(url_for(".index"))

@pages.route("/timetable/<string:_id>/delete")
@login_required
def delete_timetable(_id:str):
    if not (_id in User(**(current_app.db.user.find_one({"_id":session.get("_id")}))).timetables):
        abort(401)
    
    for subject in Timetable(**(current_app.db.timetable.find_one({"_id":_id}))).subjects:
        current_app.db.subject.delete_one({"_id":subject})
    current_app.db.timetable.delete_one({"_id":_id})
    user_data=current_app.db.user.find_one({"_id":session.get("_id")})
    user=User(**user_data)
    user.timetables.pop(user.timetables.index(_id))
    current_app.db.user.replace_one(current_app.db.user.find_one({"_id":session.get("_id")}),asdict(user))
    return redirect(url_for(".login"))


@pages.route("/timetable/<string:_id>/view")
@login_required
def view_timetable(_id:str):
    if not (_id in User(**(current_app.db.user.find_one({"_id":session.get("_id")}))).timetables):
        abort(401)
    timetable_data=current_app.db.timetable.find_one({"_id":_id})
    timetable=Timetable(**timetable_data)
    subject_data=[current_app.db.subject.find_one({"_id":sub_id}) for sub_id in timetable.subjects]
    subjects=[Subject(**subject) for subject in subject_data]
    return render_template("view.html",title="Timetable Planner - edit",subject_data=subject_data,timetable=timetable)    

@pages.route("/timetable/<string:_id>/edit",methods=["GET","POST"])
def edit_timetable(_id:str):
    if not (_id in User(**(current_app.db.user.find_one({"_id":session.get("_id")}))).timetables):
        abort(401)
    
    form=AddSubject()
    timetable_data=current_app.db.timetable.find_one({"_id":_id})

    timetable=Timetable(**timetable_data)
    subject_data=[current_app.db.subject.find_one({"_id":sub_id}) for sub_id in timetable.subjects]
    subjects=[Subject(**subject) for subject in subject_data]
    total_duration=sum([item.duration for item in subjects])
    current_app.db.timetable.update_one({"_id":_id},{"$set":{"duration":total_duration}})

    if form.validate_on_submit():
        subject=Subject(
            _id=uuid.uuid4().hex,
            name=(form.name.data).capitalize(),
            duration=form.duration.data
        )
        if (total_duration+subject.duration)>=24:
            flash("Timetable cannot be longer than 24 Hours. Take a break.","danger")
            return redirect(url_for(".edit_timetable",_id=_id))
        
        current_app.db.subject.insert_one(asdict(subject))
        current_app.db.timetable.update_one({"_id":_id},{"$push":{"subjects":subject._id}})
        return redirect(url_for(".edit_timetable",_id=_id))
    return render_template("edit.html",timetable_id=_id,form=form,subject_data=subjects,title="Timetable Planner - edit",total_duration=total_duration,name=timetable.name)

@pages.route("/timetable/<string:timetable_id>/subject/<string:subject_id>/delete")
@login_required
def delete_subject(timetable_id:str,subject_id:str):
    if not (timetable_id in User(**(current_app.db.user.find_one({"_id":session.get("_id")}))).timetables):
        abort(401)
    if not (subject_id in Timetable(**(current_app.db.timetable.find_one({"_id":timetable_id}))).subjects):
        abort(401)
    current_app.db.subject.delete_one({"_id":subject_id})
    timetable_data=current_app.db.timetable.find_one({"_id":timetable_id})
    timetable=Timetable(**timetable_data)
    timetable.subjects.pop(timetable.subjects.index(subject_id))
    current_app.db.timetable.replace_one(current_app.db.timetable.find_one({"_id":timetable_id}),asdict(timetable))
    return redirect(url_for(".edit_timetable",_id=timetable_id))

    

timetable_planner/templates/edit.html
{%extends "layout.html"%}
{%from "macros/fields.html" import render_text_field%}
{%from "macros/icons.html" import trashcan,pencil%}
{%block head_content%}
<link rel="stylesheet" href="{{url_for('static',filename='css/forms.css')}}">
<link rel="stylesheet" href="{{url_for('static',filename='css/edit.css')}}">
{%endblock%}
{%block main_content%}
<div class="title">
    <div class="title__details">
        <h1 class="title__heading">{{name}}</h1>
        <p>Duration: {{total_duration}} hour(s)</p>
    </div>
    <a class="heading__back" href="{{url_for('pages.index')}}">Back</a>
</div>

<form novalidate name="add__subject" class="form" method="post">
    {%with messages=get_flashed_messages(with_categories=true)%}
        {%-for category,message in messages-%}
            <div class="flashed__container">
            <span class="form__flash form__flash--{{category}}">{{message}}</span>
            </div>
        {%-endfor-%}
    {%endwith%}
    <div class="form__container">
        {{form.hidden_tag()}}
        {{render_text_field(form.name)}}
        {{render_text_field(form.duration)}}
        <div class="button">
            {{form.submit}}
            <a class="form__clear" href="{{url_for('pages.edit_timetable',_id=timetable_id)}}">Clear</a>
        </div>
    </div>
</form>
<div class="main__content">
    {%if subject_data%}
        <h2 class="heading">Subjects</h2>
        {%for subject in subject_data%}
            <div class="subject">
                <div class="subject__details">
                    <p class="subject__title subject__detail">{{subject.name}}</p>
                    <p class="subject__duration subject__detail">Duration: {{subject.duration}} hour(s)</p>
                </div>
                <div class="subject__options">
                    <a class="subject__delete" href="{{url_for('pages.delete_subject',timetable_id=timetable_id,subject_id=subject._id)}}">{{trashcan("subject__delete-image")}}</a>
                </div>
            </div>
        {%endfor%}
    {%else%}
        <p class="empty__message">
            You don't have any content yet.
        </p>
    {%endif%}
</div>
{%endblock%}

timetable_planner/templates/index.html
{%extends "layout.html"%}
{%from "macros/fields.html" import render_text_field%}
{%from "macros/icons.html" import trashcan,pencil%}

{%block head_content%}
     <link rel="stylesheet" href="{{url_for('static',filename='css/forms.css')}}"/>
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}"/>
{%endblock%}

{%block main_content%}
    <form novalidate name="add__timetable" class="form" method="post">
        <div class="form__container">
            {{form.hidden_tag()}}
            {{render_text_field(form.name)}}
            <div class="button">
                {{form.submit}}
                <a class="clear" href="{{url_for('pages.index')}}">Clear</a>
            </div>
        </div>
    </form>    
    <div class="main__content">
        {%if timetable_data%}
            <h2 class="heading">Timetables</h2>
            {%for timetable in timetable_data%}
                <div class="timetable">
                    <div class="timetable__details">
                        <p class="timetable__title timetable__detail">{{timetable.name}}</p>
                        <p class="timetable__duration timetable__detail">Total Duration: {{timetable.duration}} hour(s)</p>
                    </div>
                    <div class="timetable__options">
                        <a class="timetable__view  timetable__option" href="{{url_for('pages.view_timetable',_id=timetable._id)}}">View</a>
                        <a class="timetable__edit timetable__option" href="{{url_for('pages.edit_timetable',_id=timetable._id)}}">{{pencil("timetable__edit-image")}}</a>
                        <a class="timetable__delete timetable__option" href="{{url_for('pages.delete_timetable',_id=timetable._id)}}">{{trashcan("timetable__delete-image")}}</a>
                    </div>
                </div>
            {%endfor%}
        {%else%}
            <p class="empty__message">
                You haven't created any timetables yet.
            </p>
        {%endif%}
    </div>
{%endblock%}

timetable_planner/templates/layout.html
{%from "macros/icons.html" import logo%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="{{url_for('static',filename='css/reset.css')}}"/>
    <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%block head_content%}{%endblock%}
    <title>{{title}}</title>
</head>
<body>
    <header class="header">
        <div class="navbar">
            <a class="navbar__title" href="/">
                <div class="navbar__title-logo-nav">
                    {{logo("navbar__title-logo")}}
                </div>
                <div class="navbar__title-heading-nav">
                    <span class="navbar__title-heading navbar__title">Timetable Planner</span>
                </div>
            </a>
            <nav class="nav">
                {%if session.get("email")%}
                    <a class="navbar__button" href="{{url_for('pages.logout')}}">
                        <span class="navbar__button-link">Logout</span>
                    </a>
                {%else%}
                    <a class="navbar__button {{'link-active' if request.path==url_for('pages.login')}}" href="{{url_for('pages.login')}}" href="{{url_for('pages.login')}}">
                        <span class="navbar__button-link">Login</span>
                    </a>
                    <a class="navbar__button {{'link-active' if request.path==url_for('pages.register')}}" href="{{url_for('pages.register')}}">
                        <span class="navbar__button-link">Register<span>
                    </a>
                {%endif%}
            </nav>
        </div>
    </header>

    <main class="main">
        {%block main_content%}{%endblock%}
    </main>

    <footer class="footer">
        <small>Copyright &copy;2023. <a class="footer__link" href="https://github.com/Anonymous-1O1/timetable-planner">Timetable Planner</a>. All rights reserved</small>
    </footer>
</body>
</html>

timetable_planner/templates/login.html
{%from "macros/fields.html" import render_text_field%}
{%extends "layout.html"%}

{%block head_content%}
    <link rel="stylesheet" href="{{url_for('static',filename='css/forms.css')}}"/>
{%endblock%}

{%block main_content%}
<form novalidate name="login" method="post" class="form">
    {%with messages=get_flashed_messages(with_categories=true)%}
        {%-for category,message in messages-%}
            <span class="form__flash form__flash--{{category}}">{{message}}</span>
        {%-endfor-%}
    {%endwith%}

    <div class="form__container">
        {{form.hidden_tag()}}
        {{render_text_field(form.email)}}
        {{render_text_field(form.password)}}
        
        <span class="form__small">
            Don't have an account? <a href="{{url_for('pages.register')}}" class="form__link">Register here</a>.
        </span>

        <div>

            {{form.submit(class_="button button--form")}}
        </div>
    </div>
</form>
{%endblock%}

timetable_planner/templates/register.html
{%from "macros/fields.html" import render_text_field%}
{%extends "layout.html"%}

{%block head_content%}
    <link rel="stylesheet" href="{{url_for('static',filename='css/forms.css')}}"/>
{%endblock%}

{%block main_content%}
<form novalidate name="login" method="post" class="form">
    {%with messages=get_flashed_messages(with_categories=true)%}
        {%-for category,message in messages-%}
            <span class="form__flash form__flash--{{category}}">{{message}}</span>
        {%-endfor-%}
    {%endwith%}

    <div class="form_container">
        {{form.hidden_tag()}}
        {{render_text_field(form.email)}}
        {{render_text_field(form.password)}}
        {{render_text_field(form.confirm_password)}}
        
        <span class="form__small">
            Already have an account? <a href="{{url_for('pages.login')}}" class="form__link">Login here</a>.
        </span>

        <div>
            {{form.submit(class_="button button--form")}}
        </div>
    </div>
</form>
{%endblock%}

timetable_planner/templates/view.html
{%extends "layout.html"%}

{%block head_content%}
    <link rel="stylesheet" href="{{url_for('static',filename='css/view.css')}}">
{%endblock%}

{%block main_content%}
    <div class="main_content">
        <div class="title">
            <h2 class="title__heading">{{timetable.name}}</h2>
            <p class="title__duration">Total duration: {{timetable.duration}} hours(s)</p>
        </div>
        
        {%if subject_data%}
        <div class="subject">
            {%for subject in range(subject_data|length)%}
                    <div class="subject__details">
                        <h4 class="subject__title subject__detail">{{subject+1}}) {{subject_data[subject].name}}</h4>
                        <p class="subject__duration subject__detail">Duration: {{subject_data[subject].duration}} hour(s)</p>
                    </div>
            {%endfor%}
        </div>
        {%else%}
        <p class="empty__message">
            You don't have any content yet.
        </p>
        {%endif%}
        <div class="back__button">
        <a class="view__back" href="{{url_for('pages.index')}}">Back</a>
        </div>
    </div>
{%endblock%}